/*
 * App URI: addProduct
 * Source Location: addProduct.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("addProduct", {
		onPrepare: function(loader){
			loader.addCSS("theme/css/addProduct_style.css");
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * addProduct.js
			 * Created at 2022. 5. 23. 오후 10:41:02.
			 *
			 * @author PSE
			 ************************************************/
			
			/*
			 * 루트 컨테이너에서 init 이벤트 발생 시 호출.
			 * 앱이 최초 구성될 때 발생하는 이벤트 입니다.
			 */
			function onBodyInit(/* cpr.events.CEvent */ e){
				
			}
			
			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad(/* cpr.events.CEvent */ e){
				app.lookup("radio_productType").value = "출입통제기"
				var embeddedApp = app.lookup("detailLayout");
				cpr.core.App.load("addDevice", function(loadedApp){
					if(loadedApp){
			    	embeddedApp.app = loadedApp;
			  		}
				});
				
			}
			
			/*
			 * 라디오 버튼에서 selection-change 이벤트 발생 시 호출.
			 * 라디오버튼 아이템을 선택하여 선택된 값이 저장된 후에 발생하는 이벤트.
			 */
			function onRadio_productTypeSelectionChange(/* cpr.events.CSelectionEvent */ e){
				/** 
				 * @type cpr.controls.RadioButton
				 */
				var radio_productType = e.control;
				
			}
			/*
			var embeddedApp = app.lookup("detailLayout");
			var resultCode = embeddedApp.getAppProperty("resultCode")
			if (resultCode == 1) {
				app.close();
			}
			*/;
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 740px) and (max-width: 1023px)", "pop-up");
			app.supportMedia("all and (min-width: 740px) and (max-width: 739px)", "dialog");
			app.supportMedia("all and (min-width: 500px) and (max-width: 739px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"font-family" : "'\\B9D1\\C740  \\ACE0\\B515' , 'Malgun Gothic' , sans-serif",
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var embeddedApp_1 = new cpr.controls.EmbeddedApp("detailLayout");
			container.addChild(embeddedApp_1, {
				"top": "62px",
				"left": "20px",
				"width": "713px",
				"height": "818px"
			});
			
			var radioButton_1 = new cpr.controls.RadioButton("radio_productType");
			radioButton_1.style.css({
				"white-space" : "nowrap",
				"text-align" : "center"
			});
			radioButton_1.style.item.css({
				"padding-left" : "0px",
				"padding-right" : "0px"
			});
			(function(radioButton_1){
				radioButton_1.addItem(new cpr.controls.Item("출입통제기", "출입통제기"));
				radioButton_1.addItem(new cpr.controls.Item("SW", "SW"));
			})(radioButton_1);
			container.addChild(radioButton_1, {
				"top": "20px",
				"left": "20px",
				"width": "214px",
				"height": "30px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
		}
	});
	app.title = "addProduct";
	cpr.core.Platform.INSTANCE.register(app);
})();
