/*
 * App URI: product_management
 * Source Location: product_management.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("product_management", {
		onPrepare: function(loader){
			loader.addCSS("theme/css/main.css");
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * product_management.js
			 * Created at 2022. 5. 13. 오후 3:32:31.
			 *
			 * @author A
			 ************************************************/
			
			/*
			 * 루트 컨테이너에서 init 이벤트 발생 시 호출.
			 * 앱이 최초 구성될 때 발생하는 이벤트 입니다.
			 */
			
			function onBodyInit(/* cpr.events.CEvent */ e){
				
				
			}
			
			
			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad(/* cpr.events.CEvent */ e){
				// 트리 메뉴 구성을 위한 정보 가져오기
				app.lookup("getSideMenu").send();
				console.log("getSideMenu 서브 미션 실행");
			}
			
			
			
			/*
			 * 서브미션(getSideMenu)에서 submit-done 이벤트 발생 시 호출.
			 * 응답처리가 모두 종료되면 발생합니다.
			 */
			function onGetSideMenuSubmitDone(/* cpr.events.CSubmissionEvent */ e){
				/** 
				 * @type cpr.protocols.Submission
				 */
				var sub_getSideMenu = e.control;
				var sideTree = app.lookup("sideTree");
				
				
				var sideMenuList = app.lookup("sideMenuList");
				console.log("데이터 셋 : " + sideMenuList.getRowCount());
				console.log(sideMenuList);
				/*
				for(var i = 0; i < sideMenuList.getRowCount(); i++){
					sideTree.addItem(new cpr.controls.TreeItem(sideMenuList.getValue(i, "label"), sideMenuList.getValue(i, "value"), sideMenuList.getValue(i, "parent")));
				}
				
				sideTree.setItemSet(sideMenuList, {label:"label", value:"value", icon:null, parentValue:"parent"});	
				*/	
				sideTree.redraw();
				
				console.log("getSideMenu 서브 미션 완료");
				//console.log(sideTree.getItems());
				
			
				
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("sideMenuList");
			dataSet_1.parseData({
				"columns": [
					{
						"name": "label",
						"dataType": "string"
					},
					{
						"name": "value",
						"dataType": "string"
					},
					{"name": "parent"},
					{
						"name": "product_id",
						"dataType": "number"
					}
				],
				"rows": []
			});
			app.register(dataSet_1);
			var submission_1 = new cpr.protocols.Submission("getSideMenu");
			submission_1.async = true;
			submission_1.method = "get";
			submission_1.action = "/productMangement/sideMenu";
			submission_1.addResponseData(dataSet_1, false);
			if(typeof onGetSideMenuSubmitDone == "function") {
				submission_1.addEventListener("submit-done", onGetSideMenuSubmitDone);
			}
			app.register(submission_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"font-size" : "11pt",
				"background-repeat" : "no-repeat",
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px",
				"font-family" : "IBMPlexSansKR-Regular"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			// Layout
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var tree_1 = new cpr.controls.Tree("sideTree");
				tree_1.indent = 20;
				tree_1.style.css({
					"border-radius" : "15px"
				});
				(function(tree_1){
					tree_1.setItemSet(app.lookup("sideMenuList"), {
						"label": "label",
						"value": "value",
						"parentValue": "parent"
					});
				})(tree_1);
				if(typeof onTre1SelectionChange == "function") {
					tree_1.addEventListener("selection-change", onTre1SelectionChange);
				}
				if(typeof onSideTreeSelectionChange == "function") {
					tree_1.addEventListener("selection-change", onSideTreeSelectionChange);
				}
				container.addChild(tree_1, {
					"top": "7px",
					"left": "1px",
					"width": "225px",
					"height": "714px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "20px",
				"left": "19px",
				"width": "227px",
				"height": "727px"
			});
			
			var group_2 = new cpr.controls.Container();
			group_2.style.css({
				"border-right-style" : "solid",
				"border-top-width" : "1px",
				"border-bottom-color" : "#8d8d8d",
				"border-right-width" : "1px",
				"border-left-color" : "#8d8d8d",
				"border-right-color" : "#8d8d8d",
				"border-left-width" : "1px",
				"border-top-style" : "solid",
				"border-radius" : "15px",
				"border-left-style" : "solid",
				"border-bottom-width" : "1px",
				"border-top-color" : "#8d8d8d",
				"font-family" : "'\\B9D1\\C740  \\ACE0\\B515' , 'Malgun Gothic' , sans-serif",
				"border-bottom-style" : "solid"
			});
			// Layout
			var xYLayout_3 = new cpr.controls.layouts.XYLayout();
			group_2.setLayout(xYLayout_3);
			(function(container){
			})(group_2);
			container.addChild(group_2, {
				"top": "133px",
				"left": "255px",
				"width": "748px",
				"height": "614px"
			});
			
			var button_1 = new cpr.controls.Button();
			button_1.value = "제품 등록";
			button_1.style.css({
				"border-right-style" : "none",
				"background-color" : "#B8E6B8",
				"border-radius" : "10px",
				"color" : "black",
				"border-left-style" : "none",
				"font-size" : "11pt",
				"border-bottom-style" : "none",
				"background-image" : "none",
				"border-top-style" : "none"
			});
			container.addChild(button_1, {
				"top": "91px",
				"left": "893px",
				"width": "95px",
				"height": "30px"
			});
			
			var output_1 = new cpr.controls.Output();
			output_1.value = "제품관리";
			output_1.style.css({
				"font-size" : "30pt"
			});
			container.addChild(output_1, {
				"top": "33px",
				"left": "546px",
				"width": "176px",
				"height": "58px"
			});
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "product_management";
	cpr.core.Platform.INSTANCE.register(app);
})();
